default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: ubuntu

development:
  <<: *default
  database: vestige_development

test:
  <<: *default
  database: vestige_test
